name: Deploy MATHGPT

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Test MATHGPT"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Docker image
      run: |
        docker build -f docker/Dockerfile.api -t mathgpt-api:latest .
        echo "✅ Docker image built successfully"
    
    - name: Log in to Docker Hub
      if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Docker Hub
      if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
      run: |
        docker tag mathgpt-api:latest ${{ secrets.DOCKER_USERNAME }}/mathgpt-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mathgpt-api:latest
        echo "✅ Image pushed to Docker Hub"
    
    - name: Create deployment artifact
      run: |
        mkdir -p deployment-info
        echo "Deployment completed at $(date)" > deployment-info/status.txt
        echo "Image: mathgpt-api:latest" >> deployment-info/status.txt
        echo "Commit: ${{ github.sha }}" >> deployment-info/status.txt
    
    - name: Upload deployment info
      uses: actions/upload-artifact@v3
      with:
        name: deployment-info
        path: deployment-info/
    
    - name: Notify deployment status
      run: |
        echo "🚀 Deployment workflow completed!"
        echo "📊 Check deployment artifacts for details"
        echo "🔗 API will be available at your deployment URL"